blank_issues_enabled: false

contact_links:
  - name: 💬 Discussions
    url: https://github.com/khacnamdev/kn-calculator/discussions
    about: Ask questions, share ideas, or start a general discussion.
